name: flutter_template_cli
description: A CLI tool for creating Flutter projects from templates
version: 1.0.1
repository: https://github.com/enzomarc237/flutter_template_cli

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.8.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mason_logger: ^0.2.11
  pubspec_parse: ^1.2.3
  git: ^2.2.1
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
